[workspace]
members = [
    "server",
    "service",
    "pingora",
    "testing",
    "migration",
    "switchgear"
]

resolver = "2"


[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true


[patch.crates-io]
sqlx = { git = "https://github.com/bitshock-src/sqlx.git", branch = "issues-960-v0.8.6" }
sqlx-core ={ git = "https://github.com/bitshock-src/sqlx.git", branch = "issues-960-v0.8.6" }
sqlx-macros = { git = "https://github.com/bitshock-src/sqlx.git", branch = "issues-960-v0.8.6"  }
sqlx-macros-core = { git = "https://github.com/bitshock-src/sqlx.git", branch = "issues-960-v0.8.6"  }
sqlx-mysql = { git = "https://github.com/bitshock-src/sqlx.git", branch = "issues-960-v0.8.6"  }
sqlx-postgres = { git = "https://github.com/bitshock-src/sqlx.git", branch = "issues-960-v0.8.6"  }
sqlx-sqlite = { git = "https://github.com/bitshock-src/sqlx.git", branch = "issues-960-v0.8.6"  }
